### ISSUE TITLE
支持自动编号类型字段，第一步实现流水号

### ISSUE THREAD

**Issue by hotlong** [steedos/object-server#102]
参考：https://github.com/steedos/creator/issues/98
odoo 自动编号： https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/models/ir_sequence.py

**Comment by sunhaolin** [comment]
新增 自动编号 autonumber 字段类型。

type:autonumber
可设定编号公式: {yyyy}-{mm}-{0000}
自动编号字段只读

自动编号当前编号表 object_autonumber

object_name:对象名
field_name:自动编号字段
prefix:前缀
current_no:当前编号值
date_from: 日期范围开始日期
date_to：日期范围截止日期
计算字段新编号时，首先查此表，如果此表无记录，自动插入一条记录
