### ISSUE TITLE
标准业务对象完善

### ISSUE THREAD

**Issue by hotlong** [steedos/object-server#114]
清单参考：
https://github.com/steedos/object-server/blob/develop/docs/standard_objects.md

删除 
- accounts
- contacts

转换为 yml
- attachments
- permission_shares
- reports

https://github.com/steedos/creator/tree/master/packages/steedos-app-base/models
- tasks
- events
- notes

https://github.com/steedos/creator/tree/9f7ab272e144fb5f7602090cebdb4990c78df8c4/packages/steedos-app-chat
建议放到 chatter 子文件夹中

审批王相关：https://github.com/steedos/creator/tree/master/packages/steedos-app-workflow/models
建议放到 workflow 子文件夹中

**Comment by sunhaolin** [comment]
以下对象中company_id字段的require属性由之前的 Meteor.settings?.public?.is_group_company，暂修改为false，待包老师的插件实现
```js
forms
flows
flow_roles
flow_positions
instances
```
