### ISSUE TITLE
主单位 company_id / 所属单位 company_ids 业务逻辑

### ISSUE THREAD

**Issue by hotlong** [steedos/object-server#170]
- [x] 新建记录时，主单位company_id和company_ids默认值均为用户所属主单位。
- [x] 原则上应该将 company_ids 设置为可编辑。当 company_ids 可编辑时，修改 company_ids 同时更新 company_id = company_ids[0]
- [x] 考虑到兼容老项目，当 company_id 可编辑时，修改 company_id 同时更新 company_ids = [company_id]，此时 company_ids 必须只读。
- [x] 如果当前用户对当前业务对象的权限为 modifyCompanyRecords，那选择单位时只能从当前用户所属单位中选择。
- [x] 如果当前用户对当前业务对象的权限为 modifyAllRecords，那选择单位时可以能从所有单位中选择。
- [x] 需要考虑对组织结构模块的影响。

**Comment by yinlianghui** [comment]
问题：
1. 当 company_ids 可编辑时，清除company_ids值，也清除company_id值吗？
2.当 company_id 可编辑时，清除company_id值，也清除company_ids值吗？

**Comment by yinlianghui** [comment]
改动：
- base.object.yml中增加了defaultValue、optionsFunction脚本处理默认值及下拉列表可选项范围
- base.object.js中的before.update.server.default脚本增加两个单位字段间级联变更逻辑代码

**Comment by yinlianghui** [comment]
显示异常另外报issue了：https://github.com/steedos/creator/issues/1427

**Comment by yinlianghui** [comment]
关联任务：新建签约对象时所属单位默认值未成功设置上 #172 (https://github.com/steedos/steedos-project-dzug/issues/172)
