### ISSUE TITLE
放开单位表关联组织属性的编辑功能

### ISSUE THREAD

**Issue by yinlianghui** [steedos/object-server#175]
关联任务：把所属单位表 company 从 organizations 中独立出来 #124
重点：以前要求company的_id值与关联组织organization的_id值相同
实现方法：

- [x] 不完全放开编辑功能，只允许单位的organization值为空或单位的organization值不等于其_id值的记录可以编辑其organization属性值
- [x] 删除单位级联删除关联组织、删除单位级组织级联删除对应单位时应该统一用doc._id作为删除条件，即只删除_id值相等的关联记录，_id值不相等的记录不执行级联删除
- [x] 编辑关联组织时，要判断选中的关联组织是否已经被其他单位关联了，如果有就提示不能修改，而且不用处理其is_company、company_id值逻辑
- [x] 编号关联组织时，允许清除关联组织值，而且不用处理其is_company、company_id值逻辑
- [x] ”更新组织“操作按钮功能中增加一段先行逻辑：执行更新组织前先把所有company的直属关联组织is_company及is_company设置对，即把直属关联组织is_company设置为true，company_id设置为关联单位_id，同时清除未被company对象引用过的organizations记录的is_company值为false
- [x] ”更新组织“操作按钮功能要修改并重新审查一次，保证organizations.company_id, space_users.company_id, space_users.company_ids值被正常更新。

> 组织对象中的所属单位属性保持只读不可编辑，且is_company属性也保持只读不可编辑

**Comment by hotlong** [comment]
重点是确认更新组织之后，organizations.company_id, space_users.company_id, space_users.company_ids 是否正常。

**Comment by hotlong** [comment]
测试回复

**Comment by yinlianghui** [comment]
dzug项目编辑单位关联组织推荐步骤：
1.升级项目到包含本次修改的最新版本
2.执行migrage脚本中的脚本：`1568180513989-company_id.js`
3.执行后可以在单位列表中看到新建了一条我方单位记录：`大众公用`，关联到根组织`大众公用`
4.编辑所有未关联组织的我方单位记录，指定其关联组织
5.找到`大众公用`这个根级单位，执行其`更新组织`操作按钮
