### ISSUE TITLE
对象权限调整

### ISSUE THREAD

**Issue by hotlong** [steedos/object-server#182]
- unreadable_fields 作废，改为 fields
- uneditable_fields 作废，改为 fieldsEditable
- disabled_list_views 作废，改为 listViews
- unrelated_objects 作废，改为 relatedObjects
- disabled_actions 作废，改为 actions

详细规则请参考：
https://github.com/steedos/object-server/blob/develop/docs/object_permission.md

**Comment by yinlianghui** [comment]
关联任务：
- [普通用户禁用某个视图权限后，自定义权限组中用户不可以再放开该视图权限了 #206](https://github.com/steedos/steedos-project-dzug/issues/206)
- [权限判断中叠加算法需要讨论确认下是不是对的 #1422](https://github.com/steedos/creator/issues/1422)

**Comment by yinlianghui** [comment]
迁移到issue：[对象权限功能先实现fields和relatedList部分 #229](https://github.com/steedos/object-server/issues/229)
