### ISSUE TITLE
单位增加排序号字段，更新组织时从组织同步

### ISSUE THREAD

**Issue by hotlong** [steedos/object-server#211]

**Comment by yinlianghui** [comment]
总体规则：
-单位的排序号设置为omit，不能编辑
-新建单位时默认排序号值与新建组织一样为100
-执行单位的“更新组织”时，会同步所有单位的排序号值为关联组织的排序号
-变更组织的排序后后，应该在界面上手动执行下任意一个单位的“更新组织”操作
