### ISSUE TITLE
新建单位时，如果选择了关联组织，不应该再自动创建组织

### ISSUE THREAD

**Issue by hotlong** [steedos/object-server#212]

**Comment by yinlianghui** [comment]
总体规则：
-新建单位时未选择关联组织，则根组织下新建对应的组织相关联，反之不新建组织
-之前所有单位与组织_id值同步相同的逻辑全去掉了
-删除单位时有关联组织时禁止删除，只能手动清空关联组织值后再删除
-删除组织时，不级联删除单位，需要手动删除对应的单位
