### ISSUE TITLE
push.js在正式上线项目中，用浏览器、客户端确认下是否生效

### ISSUE THREAD

**Issue by yinlianghui** [steedos/object-server#230]
之前跑源码通知功能测试下来是只有输入地址为localhost才生效的，输入的是ip地址就不生效！

**Comment by yinlianghui** [comment]
测试方法：
用两个账户A、B分别在两个浏览器上登录，然后A账户上新建一个任务，分派给B，看看B是不是能收到浏览器、客户端通知！

测试要点：
两个浏览器上都用IP地址输入，不可以跑本地服务测试，最好直接用测试平台已经上线的网站地址来测试

**Comment by xucen-ai** [comment]
华信，客户端和谷歌都不能收到通知，ME浏览器可以正常收到通知

**Comment by xucen-ai** [comment]
华信客户端，审批王客户端和谷歌都不能收到通知，edge浏览器可以正常收到通知

**Comment by yinlianghui** [comment]
> * mac上的https开头的ip地址，safari、chrome、华信客户端都正常
> * win10上的https开头的ip地址，edge、chrome、华信客户端都正常，但是审批王客户端不正常
> 
> > 关于审批王客户端不正常的问题
> 
> * 经确认，控制台打印的日志是说允许接受通知的
> * 控制台执行`require("push.js").create('aaa')`是会弹出通知的！

- 上面审批王客户端不正常是因为notification.object.js中忘记调用`Steedos.isNewWindow()`函数了
- 修正后，本地localhost测试下来除了win10版本的新发布的华信客户端有问题外（老的版本是好的），其他都是好的了。

> 关于新发布的华信客户端有问题，是因为控制台执行`require("push.js").create('aaa')`不是会弹出通知的了！
