### ISSUE TITLE
业务对象新增开关, enable_workflow

### ISSUE THREAD

**Issue by hotlong** [steedos/object-server#258]
只有启用此开关的业务对象，才能显示在对象流程的配置菜单中。

**Comment by hotlong** [comment]
开发完成后，请@troy 测试，并更新业务对象开发文档

**Comment by baozhoutao** [comment]
此对象上的field_map_script， field_map_back_script 2个字段脚本是在server端运行的，请使用require('eval') ，限制脚本中可以访问的对象。防止乱写脚本。
